/* Generated By:JJTree: Do not edit this line. ASTAssignment.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAssignment extends SimpleNode {

  public boolean array = false;

  public ASTAssignment(int id) {
    super(id);
  }

  public ASTAssignment(Parser p, int id) {
    super(p, id);
  }

  /**
   * Accept the visitor.
   **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
            visitor.visit(this, data);
  }

  public String toString() {
    return "Assignment" + (array ? " []" : "");
  }

}/* JavaCC - OriginalChecksum=2a332975fe9c36f4cbbd670027f17fff (do not edit this line) */
