/* Generated By:JJTree: Do not edit this line. ASTid.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTid extends SimpleNode {
  public ASTid(int id) {
    super(id);
  }

  public ASTid(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }

  public String toString() {
    return "id: " + super.value;
  }
}
/* JavaCC - OriginalChecksum=67888e5a97626e16047536c55c99e468 (do not edit this line) */
