/* Generated By:JJTree: Do not edit this line. ASTRegularMethod.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTRegularMethod extends SimpleNode {
  public ASTRegularMethod(int id) {
    super(id);
  }

  public ASTRegularMethod(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }

  public String toString() {
    return "Regular Method: " + super.value;
  }
}
/* JavaCC - OriginalChecksum=e08b2dc5e8f406e2bdfe3077230034be (do not edit this line) */
