/* Generated By:JavaCC: Do not edit this line. CalculatorTreeConstants.java Version 6.0_1 */
public interface CalculatorTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTASSIGNMENT = 1;
  public int JJTEXPR1 = 2;
  public int JJTEXPR2 = 3;
  public int JJTEXPR3 = 4;


  public String[] jjtNodeName = {
    "Expression",
    "Assignment",
    "Expr1",
    "Expr2",
    "Expr3",
  };
}
/* JavaCC - OriginalChecksum=12639fe0d66f6ce3da58413ecfeea42b (do not edit this line) */
