/* Generated By:JavaCC: Do not edit this line. CalculatorTreeConstants.java Version 7.0.4 */
public interface CalculatorTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTASSIGNMENT = 1;
  public int JJTVOID = 2;
  public int JJTADD = 3;
  public int JJTSUB = 4;
  public int JJTEXPR2 = 5;
  public int JJTMUL = 6;
  public int JJTDIV = 7;
  public int JJTTERM = 8;


  public String[] jjtNodeName = {
    "Expression",
    "Assignment",
    "void",
    "Add",
    "Sub",
    "Expr2",
    "Mul",
    "Div",
    "Term",
  };
}
/* JavaCC - OriginalChecksum=ab3786b7d61b945b185b4a1677a79381 (do not edit this line) */
