/* Generated By:JavaCC: Do not edit this line. CalculatorTreeConstants.java Version 7.0.4 */
public interface CalculatorTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTASSIGNMENT = 1;
  public int JJTEXPR1 = 2;
  public int JJTEXPR2 = 3;
  public int JJTEXPR3 = 4;


  public String[] jjtNodeName = {
    "Expression",
    "Assignment",
    "Expr1",
    "Expr2",
    "Expr3",
  };
}
/* JavaCC - OriginalChecksum=d03d8f2848345310ee13008cd61692f6 (do not edit this line) */
