/* Generated By:JJTree: Do not edit this line. AST_new.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class AST_new extends SimpleNode {
  public boolean isArray = false;
  public String primId;

  public AST_new(int id) {
    super(id);
  }

  public AST_new(Parser p, int id) {
    super(p, id);
  }

  public String toString() {
    if (isArray) {
      return "_new: new int[]";
    }
    else {
      return "_new: new " + primId + "()";
    }
  }

}
/* JavaCC - OriginalChecksum=2488efcd08b581ea0bfba40ba9ae5fca (do not edit this line) */
