/* Generated By:JJTree: Do not edit this line. ASTand.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTand extends SimpleNode {
  public ASTand(int id) {
    super(id);
  }

  public ASTand(Parser p, int id) {
    super(p, id);
  }

  @Override
  public void analyse(SemanticAnalyser analyser) throws SemanticException {
    analyser.analyseAnd(this);
  }

  @Override
  public String getType() {
    return "boolean";
  }
}
/* JavaCC - OriginalChecksum=75bcf2d271e5c1e20b566ebf638b3209 (do not edit this line) */
