/* Generated By:JJTree: Do not edit this line. ASTbool.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTbool extends SimpleNode {

  public boolean value = false;

  public ASTbool(int id) {
    super(id);
  }

  public ASTbool(Parser p, int id) {
    super(p, id);
  }

  public String toString() {
    return "Boolean: " + value;
  }
}
/* JavaCC - OriginalChecksum=c0ce3381abd6f4b6829e72d98ac633a3 (do not edit this line) */
