/* Generated By:JJTree: Do not edit this line. ASTbool.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTbool extends SimpleNode {
  public ASTbool(int id) {
    super(id);
  }

  public ASTbool(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }

  public String toString() {
    return "Boolean: " + super.value;
  }
}
/* JavaCC - OriginalChecksum=67b90c309449ed835e49b56a2b43a7c4 (do not edit this line) */
