/* Generated By:JJTree: Do not edit this line. ASTCallMethod.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCallMethod extends SimpleNode {

  public String methodId;

  public ASTCallMethod(int id) {
    super(id);
  }

  public ASTCallMethod(Parser p, int id) {
    super(p, id);
  }

  public String toString() {

    return "CallMethod: " + methodId;
  }
}
/* JavaCC - OriginalChecksum=c30a76cb2986ecc8315563f8911ff379 (do not edit this line) */
