/* Generated By:JJTree: Do not edit this line. ASTClassDeclaration.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTClassDeclaration extends SimpleNode {
  public String classId;
  public String extId;

  public int extLine;
  public int extColumn;

  public ASTClassDeclaration(int id) {
    super(id);
  }

  public ASTClassDeclaration(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }

  public String toString() {
    return "ClassDeclaration: class " + classId + " " + ((extId != null) ? ("extends " + extId) : "");
  }

  @Override
  public Object jjtGetValue() {
    return this.classId;
  }
}
/* JavaCC - OriginalChecksum=a9052b063bb615c0e3e8421fb3251526 (do not edit this line) */
