/* Generated By:JJTree: Do not edit this line. ASTinteger.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTinteger extends SimpleNode {

  public String value;

  public ASTinteger(int id) {
    super(id);
  }

  public ASTinteger(Parser p, int id) {
    super(p, id);
  }

  public String toString() {
    return "Integer: " + value;
  }
}
/* JavaCC - OriginalChecksum=f2c5b5726d9dee22dffb5df1703c9cbd (do not edit this line) */
