/* Generated By:JJTree: Do not edit this line. ASTImportMethod.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTImportMethod extends SimpleNode {

  public String methodId;

  public ASTImportMethod(int id) {
    super(id);
  }

  public ASTImportMethod(Parser p, int id) {
    super(p, id);
  }

  public String toString() {
    return "ImportMethod: " + methodId;
  }

}
/* JavaCC - OriginalChecksum=cce58d9d6e5aa1c7c7c73afdb4ccffe9 (do not edit this line) */
