/* Generated By:JJTree: Do not edit this line. ASTImport.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTImport extends SimpleNode {

  public boolean isStatic = false;
  public String importId;
  public boolean isMethod = false;
  public String methodId;
  public String returnType = "void";

  public ASTImport(int id) {
    super(id);
  }

  public ASTImport(Parser p, int id) {
    super(p, id);
  }

  public String toString() {
    String out = "Import: " + (isStatic ? "static " : "") + importId;
    if (isMethod) {
      out += "." + methodId + " - returns " + returnType;
    }
    return out;
  }

}
/* JavaCC - OriginalChecksum=102b8623e78d8554f34992788a15d8e1 (do not edit this line) */
