/* Generated By:JJTree: Do not edit this line. ASTMethodParam.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMethodParam extends SimpleNode {
  public String paramId;

  public ASTMethodParam(int id) {
    super(id);
  }

  public ASTMethodParam(Parser p, int id) {
    super(p, id);
  }

  public String toString() {
    return "Method parameter: " + paramId;
  }
}
/* JavaCC - OriginalChecksum=7a44c9c0563ef1a4dd94c7a385073111 (do not edit this line) */
