/* Generated By:JJTree: Do not edit this line. ASTMethodParam.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMethodParam extends SimpleNode {
  public ASTMethodParam(int id) {
    super(id);
  }

  public ASTMethodParam(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }

  public String toString() {
    return "Method parameter: " + super.value;
  }
}
/* JavaCC - OriginalChecksum=e06dad724e22125548dc3cd2ebc6340e (do not edit this line) */
