/* Generated By:JJTree: Do not edit this line. ASTMainParams.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMainParams extends SimpleNode {
  public ASTMainParams(int id) {
    super(id);
  }

  public ASTMainParams(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }

  public String toString() {
    return "Main parameter: " + super.value;
  }
}
/* JavaCC - OriginalChecksum=3d506bcb9034e8c6af9280453944bf3e (do not edit this line) */
