/* Generated By:JJTree: Do not edit this line. ASTMainParams.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMainParams extends SimpleNode {
  public String paramId;

  public ASTMainParams(int id) {
    super(id);
  }

  public ASTMainParams(Parser p, int id) {
    super(p, id);
  }

  public String toString() {
    return "Main parameter: " + paramId;
  }
}
/* JavaCC - OriginalChecksum=aa0e2ba0185f88540e91f0266ea7fc9c (do not edit this line) */
