/* Generated By:JJTree: Do not edit this line. ASTRegularMethod.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTRegularMethod extends SimpleNode {
  public String methodId;

  public ASTRegularMethod(int id) {
    super(id);
  }

  public ASTRegularMethod(Parser p, int id) {
    super(p, id);
  }

  public String toString() {
    return "Regular Method: " + methodId;
  }
}
/* JavaCC - OriginalChecksum=e4753ca2d65941be9bf059123373c20d (do not edit this line) */
