/* Generated By:JJTree: Do not edit this line. ASTReturnType.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTReturnType extends SimpleNode {
  public String type;
  public boolean array = false;

  public ASTReturnType(int id) {
    super(id);
  }

  public ASTReturnType(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }

  public String toString() {
    return "Returns: " + type + (array ? "[]" : "");
  }

  @Override
  public Object jjtGetValue() {
    return type + (array ? "[]" : "");
  }

}
/* JavaCC - OriginalChecksum=636d4506d63fa3d84c9b128bfcf80586 (do not edit this line) */
