/* Generated By:JJTree: Do not edit this line. ASTStatement.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStatement extends SimpleNode {

  public String type;
  public String id;
  public boolean array = false;
  public boolean assign = false;

  public ASTStatement(int id) {
    super(id);
  }

  public ASTStatement(Parser p, int id) {
    super(p, id);
  }

  public String toString() {
    return "Statement: " + type + ((id != null) ? (" " + id) : "") + (array ? "[]" : "") + (assign ? " =" : "");
  }

}
/* JavaCC - OriginalChecksum=4e455c425c0f2f9e2dfa6e5cfd01c36a (do not edit this line) */
