/* Generated By:JJTree: Do not edit this line. ASTType.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTType extends SimpleNode {
  public String type;
  public boolean array = false;

  public ASTType(int id) {
    super(id);
  }

  public ASTType(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }

  public String toString() {
    return "Type: " + type + (array ? "[]" : "");
  }

  @Override
  public Object jjtGetValue() {
    return type + (array ? "[]" : "");
  }
}
/* JavaCC - OriginalChecksum=076e5533aa36f31d12d52520881ff7b5 (do not edit this line) */
