/* Generated By:JJTree: Do not edit this line. ASTVarDeclaration.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVarDeclaration extends SimpleNode {

  public String id;

  public ASTVarDeclaration(int id) {
    super(id);
  }

  public ASTVarDeclaration(Parser p, int id) {
    super(p, id);
  }

  public String toString() {
    return "VarDeclaration: " + id;
  }

}
/* JavaCC - OriginalChecksum=6f2c131a0909e861e826b68fd6544de1 (do not edit this line) */
