/* Generated By:JavaCC: Do not edit this line. CalculatorTreeConstants.java Version 5.0 */
public interface CalculatorTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTEXPR1 = 1;
  public int JJTEXPR2 = 2;
  public int JJTEXPR3 = 3;


  public String[] jjtNodeName = {
    "Expression",
    "Expr1",
    "Expr2",
    "Expr3",
  };
}
/* JavaCC - OriginalChecksum=d493687f6b5adfe4075d1b76b792a05d (do not edit this line) */
